version: "3.8"

networks:
  qrapp-network:

services:
  api:
    container_name: qrapp_api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: 8100
      HOST: "0.0.0.0"
    ports:
      - 8100:8100
#    networks:
#      - qrapp-network
    # This is crucial for application to access DB container
    links:
      - db:db
      - mongodb:mongodb
    depends_on:
      - mongodb
#      - db
    volumes:
      - ./api/src:/usr/src/api/src

  mongodb:
    container_name: qrapp_mongo
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: qrapp_user
      MONGO_INITDB_ROOT_PASSWORD: verysecret

  db:
    container_name: qrapp_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "qrapp"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "verysecret"
    ports:
      - "4306:3306"
    expose:
      - "4306"
#    networks:
#      - qrapp-network
    volumes:
      - app-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
        #    ADD setup.sql /docker-entrypoint-initdb.d

volumes:
  app-db:

